### ISSUE TITLE
TypeError: Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by humphd** [IonicaBizau/gm-tools#8]
I'm not entirely sure where this bug should live, but I'll start here and you can move it if necessary. 
 I'm playing with https://github.com/IonicaBizau/image-to-ascii, and it's working great (thank you).  When I put my code in an express app, things work, but I also see this stack on my server's console:

```
TypeError: Cannot read property 'constructor' of null
    at new GmParser (/Users/humphd/repos/learn-travis/node_modules/gm-tools/lib/index.js:29:18)
    at gmTools (/Users/humphd/repos/learn-travis/node_modules/gm-tools/lib/index.js:234:12)
    at /Users/humphd/repos/learn-travis/node_modules/image-parser/lib/index.js:60:33
    at lwipify (/Users/humphd/repos/learn-travis/node_modules/lwipify/lib/index.js:70:9)
    at ImageParser.parse (/Users/humphd/repos/learn-travis/node_modules/image-parser/lib/index.js:56:13)
    at /Users/humphd/repos/learn-travis/node_modules/image-to-ascii/lib/index.js:98:40
    at doSeq (/Users/humphd/repos/learn-travis/node_modules/one-by-one/lib/index.js:44:15)
    at oneByOne (/Users/humphd/repos/learn-travis/node_modules/one-by-one/lib/index.js:66:5)
    at imageToAscii (/Users/humphd/repos/learn-travis/node_modules/image-to-ascii/lib/index.js:97:5)
    at convert (/Users/humphd/repos/learn-travis/src/image.js:20:3)
```

This is happening here in the `gm-tools` code:

```js
    function GmParser(input, cb) {
        _classCallCheck(this, GmParser);

        this.input = input;

        if (input.constructor.name === "gm") {  // <-- `input` is null
```

This is caused by this:

```js
    // from image-parser/lib/index.js

    _createClass(ImageParser, [{
        key: "parse",
        value: function parse(cb) {
            var _this = this;

            if (this._parseBuffer.check(cb)) {
                return;
            }
            lwipify(this.source, this.options, function (err, data, options) {
                if (err) {
                    //if (err.message === "Invalid PNG buffer" || err.message === "I\
nvalid source" || /Unknown type/.test(err.message)) {
                    _this[_this.parser = "gm"] = true;
                    _this.img = gmTools(options.source);
```

In my case, the `err` above is defined: `Error: Failed to load lwip. Use GraphicsMagick instead.` (I'm using graphicsmagick because `install.js` failed).  So it goes into this error block, and `data` is `undefined`, while `options` is `{source: null}`.

Without tracing everything through all the various modules, it looks like it fails and then recovers using a fallback image handler; however, it still spits out an unnecessary stack trace somewhere along the way.

**Comment by humphd** [comment]
This turns out to be an issue with how the code is called via routes in express, closing.

Thanks again for these modules, they are a lot of fun.

**Comment by IonicaBizau** [comment]
You're welcome! Enjoy using them and don't hesitate to open issues if you find any bugs/features/suggestions/whatever. :grin:
